### Create a new category
POST http://localhost:4000/v1/categories
Content-Type: application/json

{
    "name": "coding",
    "color": "#4437f5",
    "user_id": 1
}

### Get category by id
GET http://localhost:4000/v1/categories/17

### Patch category by id
PATCH http://localhost:4000/v1/categories/6
Content-Type: application/json

{
    "name": "work"
}

### Get categories by userId
GET http://localhost:4000/v1/users/1/categories

### Delete category by id
DELETE http://localhost:4000/v1/categories/17

### Create a new task
POST http://localhost:4000/v1/tasks
Content-Type: application/json

{
    "name": "Complete college work",
    "description": "Finish the TaskLogger API implementation",
    "status": "In Progress",
    "priority": 2,
    "image": "",
    "deadline": "2027-12-31T23:59:59Z",
    "user_id": 1,
    "category_id": 18
}

### Get task by id
GET http://localhost:4000/v1/tasks/7

### Update task by id
PATCH http://localhost:4000/v1/tasks/7
Content-Type: application/json

{
    "name": "Complete this project",
    "status": "In Progress",
    "priority": 1,
    "image": ";aljdfiopehgrnmha;jklodhfghlakshjgdfjh",
    "deadline": "2025-05-15T23:59:59Z",
    "category_id": 6
}

### Delete task by id
DELETE http://localhost:4000/v1/tasks/7
